[package]
name = "gameboy"
version = "0.1.0"
authors = ["nwessing <nwessing3@gmail.com>"]
build = "build.rs"
editions = "2018"

[dependencies]
sdl2 = "0.31"
time = "*"

[profile.dev]
opt-level = 1
debug = true
